export const themes = {
  default: {
    primary: '#C70039',
    background: '#F7F7F7',
    surface: '#FFFFFF',
    textPrimary: '#1C1C1E',
    textSecondary: '#666666',
    error: '#B00020',
    success: '#4CAF50',
    border: '#E0E0E0',
    white: '#FFFFFF',
  },
  dark: {
    primary: '#BB86FC',
    background: '#121212',
    surface: '#1E1E1E',
    textPrimary: '#FFFFFF',
    textSecondary: '#A0A0A0',
    error: '#CF6679',
    success: '#66BB6A',
    border: '#2E2E2E',
    white: '#FFFFFF',
  },
  forest: {
    primary: '#4CAF50',
    background: '#F1F8E9',
    surface: '#FFFFFF',
    textPrimary: '#2E7D32',
    textSecondary: '#558B2F',
    error: '#D32F2F',
    success: '#388E3C',
    border: '#C8E6C9',
    white: '#FFFFFF',
  },
  ocean: {
    primary: '#03A9F4',
    background: '#E1F5FE',
    surface: '#FFFFFF',
    textPrimary: '#01579B',
    textSecondary: '#0288D1',
    error: '#D32F2F',
    success: '#388E3C',
    border: '#B3E5FC',
    white: '#FFFFFF',
  },
  sunset: {
    primary: '#FF7043',
    background: '#FFF3E0',
    surface: '#FFFFFF',
    textPrimary: '#E64A19',
    textSecondary: '#F57C00',
    error: '#D32F2F',
    success: '#388E3C',
    border: '#FFE0B2',
    white: '#FFFFFF',
  },
  amethyst: {
    primary: '#9C27B0',
    background: '#F3E5F5',
    surface: '#FFFFFF',
    textPrimary: '#6A1B9A',
    textSecondary: '#8E24AA',
    error: '#D32F2F',
    success: '#388E3C',
    border: '#E1BEE7',
    white: '#FFFFFF',
  },
};
